### ISSUE TITLE
Make main game class singleton?

### ISSUE THREAD

**Issue by Jarlius** [matys18/Inda-project#17]
Tinkering with changing game state from play mode to menu mode, it makes me realize many different classes needs to be able to change the state, they all need access to the main game class.
Should the main game class be static, so that all other gain access to the needed information? Does that mean we need to make it a singleton?
Or maybe better yet, make a singleton State class, which all may edit and contains a state field (also get and set methods) ? Or am I overthinking things way too much?

**Comment by matys18** [comment]
If by "Main class" you mean the "MyGdxGame" class, then no. It should stay as it is because it is supposed to be the root of the project structure, that creates and launches all other resources. However the state changing(for example between the menu and the actual game) that you have been talking about can be achieved by using the [Screens](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/Screen.html) class. Each Screen has it's own lifecycle and state, etc. There is a decent example of it [here](https://github.com/libgdx/libgdx/wiki/Extending%20the%20Simple%20Game).

Oh and if you run the code from the develop branch you will see something cool now 😄

**Comment by Jarlius** [comment]
Woah lots of code! I'll run it when I get home

**Comment by matys18** [comment]
Closed as of #18
