### ISSUE TITLE
New Game button does not work

### ISSUE THREAD

**Issue by matys18** [matys18/Inda-project#32]
Title says it all, I can't start a new game, only resume one. 😕 Could you look into that?

**Comment by Jarlius** [comment]
I noticed it before, but I had no idea what caused it so I decided to solve it later.

The `UserInput` now filters away all the unnecessary `NoSuchMethodException` (whenever you press a key that the control hasn't implemented - not a problem, but there tends to be a lot of them) and prints out the cause of `InvocationTargetException`, which are thrown by the method itself.

The exception received then is this:
`java.lang.RuntimeException: No OpenGL context found in the current thread.`
Which is in the `GameScreen` constructor, the line:
`shapes = new ShapeRenderer();`

So for some reason, the main thread from `Game` can create the `GameScreen` class with OpenGL context, but the thread from `UserInput` cannot? Is there a way to fix this?

Perhaps the `MenuControl` class needs to follow the main thread instead of creating its own, whenever a key is pressed. Concurrency isn't really needed in the menu, after all.

**Comment by Jarlius** [comment]
Oh - I tested to see if `MenuControl` would work without threads being created in `UserInput`, but as it turns out, concurrent `GameControl` works too, probably because of multithreading internally inherited by `InputProcessor`.

By removing the second layer of threads in `UserInput`, this bug :beetle: has been squashed :hammer:
