### ISSUE TITLE
Implement win/loss text

### ISSUE THREAD

**Issue by matys18** [matys18/Inda-project#41]
If you look at our GameScreen it now features two new functions win() and gameOver(). These functions are called when the player wins or looses. Since you @Jarlius are familiar with text and input,  could you make these functions draw appropriate text on the screen and disable the user input? 😇

**Comment by Jarlius** [comment]
Will do :+1:

**Comment by Jarlius** [comment]
I found it better to set the end game text as separate screens instead. The gameover screen isn't called yet, but it is ready to be let `loose()`.

**Comment by matys18** [comment]
Haha. Holy potatoes, that was really good! Great job!! 😮 👍 😄 🎉 🎈

Also I added a camera to the EndScreen so that it renders correctly no matter what the screen size is. 👍

**Comment by matys18** [comment]
If you want to test out the gameOver screen you can set the timer incrementation in `GameScreen -> render()` to be like `timer -= 10 instead`. Just remember to change it back 👍  If you want to test the winning screen... well you will have to find the exit 😆

**Comment by Jarlius** [comment]
Thanks! The Fade turned out really well I think :astonished: 

Oh and to test the gameOver I just set it to a key, while I was developing - but the light reduction works really well also! Especially as you'll crash into walls a lot at the end, adding even more to the feeling of impending doom :fearful:
