### ISSUE TITLE
Implement Walls

### ISSUE THREAD

**Issue by Jarlius** [matys18/Inda-project#5]
Prevent player controlled model from passing through walls and boundaries of map.

**Comment by matys18** [comment]
This is the next step in the project. As of right now, the entity that represents the player is a box2d DynamicBody with a PointLight attached to it. Since it uses box2d, collisions should happen automatically as long as the walls are also box2d entities(StaticBodies I think?). 💭 

The benefit to using box2d is that then we can use box2dlights which give us the nice dark-shadow effect that we want. 😄

**Comment by Jarlius** [comment]
Will walls be placed along the edges of the map too, or should there be some way to prevent player movement there regardless?

**Comment by matys18** [comment]
I'm working on the walls right now, there will be walls at the edges. I have some nice collisions going on 😄  I'll push it within the hour

**Comment by matys18** [comment]
Ok, it's up! There is a WallModel and a single Wall in the game, to the far left of the centre with working collisions and everything. The way I was thinking of doing it is simply having an ArrayList full of walls, and then just rendering them onto the screen. What do you think?

I'm done for tonight, take a crack at building more walls if you are up for it 😸

**Comment by Jarlius** [comment]
Woah! That was quick :+1: 
Looks perfect! And yeah, it won't be too many walls anyways - if we implement a scrollable screen we would maybe need to only load walls in close proximity, but right now it might be too much trouble.

Beside walls we also need to implement the "goal" :football: , that saves the time and puts it up on a scoreboard, but playing around making mazes might be more fun!

**Comment by matys18** [comment]
The rendering thing is a good idea, but I wouldn't worry about it too much at the moment 👍 Lets focus on just putting the walls up

**Comment by matys18** [comment]
As of 1613d7c0f6385358784cc3224d9516d640e5f814, we have some nice `Level` classes. The idea is that `LevelModel` defines the bounding walls of the map, and the classes that extend `Level` define more walls that are specific to that particular level. 

If you pull from develop now, you should be able to see the entire level and the bounding walls. Don't worry about the movement speed and lighting stuff for now, the actual game will be zoomed and way, way darker 😄 This is just so we can see where we put the walls.

Could you design the `Level1` class so that we have more walls? It's the first level so it does not have to be super complicated 👍 To add a wall simply add a new `WallModel` to the obstacles array in the constructor of `Level1`.  The difficult part is deciding how the level should look like 🔢 

Make sure to leave a lot of space, so that the player can get lost in the dark 😄  The "thickness" of the walls at the moment is `10f` but they don't all have to be like that, if you want to be creative 🎨 

I'll try to get sounds working in the meanwhile 🔉

**Comment by Jarlius** [comment]
I will be a bit busy until the evening, but I'll do my best :construction_worker:

**Comment by matys18** [comment]
@Jarlius There is no rush, take your time ⌚

**Comment by Jarlius** [comment]
First maze is done! :tada:

**Comment by matys18** [comment]
Nice job! We only need one maze for now.
